### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by jakirkham** [euske/pdfminer#142]
It would be great if this included a license file. According to the MIT license terms, one is suppose to include the license file with the software. However, it is a bit challenging to do that without actually having the license file somewhere. Is it possible we could add it to this repo?

cc @pmlandwehr

**Comment by euske** [comment]
Added LICENSE at 647a6c653cb05c6d74a13a462672aeaf03c2a7d3

**Comment by jakirkham** [comment]
Could it please be added to `MANIFEST.in` too?

**Comment by euske** [comment]
Done!

**Comment by jakirkham** [comment]
Thanks. 😀

**Comment by jakirkham** [comment]
When is the next release planned?
