### ISSUE TITLE
pdf2txt error in command line cannot match the files parameter

### ISSUE THREAD

**Issue by stevewyl** [euske/pdfminer#164]
Using: Pdfminer.six Python 3.5.2
I was trying to run the code in command line  like:
C:\Users\Subnotebook\Desktop>**`pdf2txt.py -o text.txt simple1.pdf`** (I have put simple1.pdf on the desktop)
But it always shows this error below:
**pdf2txt.py: error: the following arguments are required: files**
Does anyone know how to deal with this problem? Thanks!

**Comment by maxkoe** [comment]
I run into the exact same Problem

Using:
pdfminer.six 20181108
python 3.6.4 (Anaconda)
Windows 7

**Comment by krishna-koundinya** [comment]
> Using: Pdfminer.six Python 3.5.2
> I was trying to run the code in command line like:
> C:\Users\Subnotebook\Desktop>**`pdf2txt.py -o text.txt simple1.pdf`** (I have put simple1.pdf on the desktop)
> But it always shows this error below:
> **pdf2txt.py: error: the following arguments are required: files**
> Does anyone know how to deal with this problem? Thanks!

**Comment by krishna-koundinya** [comment]
> Using: Pdfminer.six Python 3.5.2
> I was trying to run the code in command line like:
> C:\Users\Subnotebook\Desktop>**`pdf2txt.py -o text.txt simple1.pdf`** (I have put simple1.pdf on the desktop)
> But it always shows this error below:
> **pdf2txt.py: error: the following arguments are required: files**
> Does anyone know how to deal with this problem? Thanks!

Running into the same issue. @stevewyl did you find a solution?
