### ISSUE TITLE
Question: Can pdfminer retrieve text & bboxes without layout?

### ISSUE THREAD

**Issue by mark-summerfield** [euske/pdfminer#177]
Is it possible to just retrieve all the text on the page with each fragment returned with its bounding box, i.e., (x1, y1, x2, y2, text) -- with no layout analysis? Use case: this would be ideal for people who want to do their own layout analysis.

**Comment by goodmami** [comment]
Does the `-n` option ('suppress layout analysis') of pdf2txt.py work for you? Combined with the `-t xml` option, it outputs XML with elements for each page and glyph, but without analysis to group glyphs into words, lines, paragraphs, etc.. For example:

```xml
...
<page id="10" bbox="0.000,0.000,504.000,1080.000" rotate="0">
<text font="" bbox="68.512,852.184,72.995,862.190" size="10.007">1</text>
<text font="" bbox="72.995,852.184,77.478,862.190" size="10.007">0</text>
<text font="" bbox="116.332,852.291,119.820,862.298" size="10.007">s</text>
<text font="" bbox="120.716,852.291,125.701,862.298" size="10.007">y</text>
<text font="" bbox="126.597,852.291,132.075,862.298" size="10.007">n</text>
...
```

**Comment by crosshair8912** [comment]
I know your struggle mark!
I did it via updating utils.py (bbox2str function) and converter.py (TextConverter class)

`class TextConverter(PDFConverter):

    def __init__(self, rsrcmgr, outfp, codec='utf-8', pageno=1, laparams=None,
                 showpageno=False, imagewriter=None):
        PDFConverter.__init__(self, rsrcmgr, outfp, codec=codec, pageno=pageno, laparams=laparams)
        self.showpageno = showpageno
        self.imagewriter = imagewriter
        return

    def write_text(self, text):
        self.outfp.write(text.encode(self.codec, 'ignore'))
        return
    def append_to_list(self, text):
        self.outfp.append(text.encode(self.codec, 'ignore'))
        return
		
    def receive_layout(self, ltpage):
        for i in ltpage:
            for j in i:
				self.append_to_list('bbox|'+bbox2str(j.bbox)+'|'+j.get_text())
        if self.showpageno:
            self.append_to_list('Page %s\n' % ltpage.pageid)
        self.append_to_list('*\n')
        return
    
    # Some dummy functions to save memory/CPU when all that is wanted
    # is text.  This stops all the image and drawing ouput from being
    # recorded and taking up RAM.
    def render_image(self, name, stream):
        if self.imagewriter is None:
            return
        PDFConverter.render_image(self, name, stream)
        return

    def paint_path(self, gstate, stroke, fill, evenodd, path):
        return`

**Comment by mark-summerfield** [comment]
goodmami: I only just saw your comment, and yes, it works perfectly with one test file.
Thanks!

**Comment by finch-wren** [comment]
> I know your struggle mark!
> I did it via updating utils.py (bbox2str function) and converter.py (TextConverter class)
> 
> `class TextConverter(PDFConverter):
> 
> ```
> def __init__(self, rsrcmgr, outfp, codec='utf-8', pageno=1, laparams=None,
>              showpageno=False, imagewriter=None):
>     PDFConverter.__init__(self, rsrcmgr, outfp, codec=codec, pageno=pageno, laparams=laparams)
>     self.showpageno = showpageno
>     self.imagewriter = imagewriter
>     return
> 
> def write_text(self, text):
>     self.outfp.write(text.encode(self.codec, 'ignore'))
>     return
> def append_to_list(self, text):
>     self.outfp.append(text.encode(self.codec, 'ignore'))
>     return
> 	
> def receive_layout(self, ltpage):
>     for i in ltpage:
>         for j in i:
>             self.append_to_list('bbox|'+bbox2str(j.bbox)+'|'+j.get_text())
>     if self.showpageno:
>         self.append_to_list('Page %s\n' % ltpage.pageid)
>     self.append_to_list('*\n')
>     return
> 
> # Some dummy functions to save memory/CPU when all that is wanted
> # is text.  This stops all the image and drawing ouput from being
> # recorded and taking up RAM.
> def render_image(self, name, stream):
>     if self.imagewriter is None:
>         return
>     PDFConverter.render_image(self, name, stream)
>     return
> 
> def paint_path(self, gstate, stroke, fill, evenodd, path):
>     return`
> ```

How to get the ltpage attribute to call the receive_layout method?
