### ISSUE TITLE
pdfminer failed using pyintaller

### ISSUE THREAD

**Issue by Starfruit007** [euske/pdfminer#204]
I try to using pyinstaller to Freeze (package) Python programs into stand-alone executables, but it was failed. The problems are as follows (There would be no problem, when I did not import pdfminer):

OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp36-win_amd64.pyd': Failed to load dynlib/dll 'C:\\Users\\HP\\AppData\\Local\\Temp\\_MEI116442\\Crypto\\Util\\..\\Cipher\
\_raw_ecb.cp36-win_amd64.pyd'. Most probably this dynlib/dll was not found when the application was frozen., Trying '_raw_ecb.pyd': Failed to load dynlib/dll 'C:\\Users\\HP\\AppData\\Local\\Temp\\_MEI
116442\\Crypto\\Util\\..\\Cipher\\_raw_ecb.pyd'. Most probably this dynlib/dll was not found when the application was frozen.
[1324] Failed to execute script Pdf2Excel

can anyone help me with that? thanks very much.

**Comment by dmiranda2791** [comment]
Did you find a solution for this problem? I'm facing the same thing. I'd really appreciate some help 😅
