### ISSUE TITLE
Use lzma instead of gzip

### ISSUE THREAD

**Issue by KOLANICH** [euske/pdfminer#206]
It gives better compression.

**Comment by KOLANICH** [comment]
https://github.com/pdfminer/pdfminer.six/pull/115

**Comment by pietermarsman** [comment]
Hi @kolanich, is there any particular reason why you need better compression?

According to https://tukaani.org/lzma/benchmarks.html lzma might have better compression, it also use more memory and is slower. If you really need better compression, I suggest that we support both compression methods.

**Comment by KOLANICH** [comment]
>is there any particular reason why you need better compression?

perfectionism. I have tried it on a pretty old machine with celeron and was satisfied with unpacking performance. I haven't done measurements on the delay, but I haven't noticed that it had changed.
