### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'PDFObjRef' and 'int'

### ISSUE THREAD

**Issue by speedplane** [euske/pdfminer#26]
When running pdfminer.get_pages on the pdf at the link below, you get the following exception:

```
  File "C:\Users\speedplane\Documents\Work\2010 - 2011\Programs\DocketUpdater\..\DocketUpdater\libs\pdfminer\pdfparser.py", line 518, in get_pages
    yield PDFPage(self, pageid, tree)
  File "C:\Users\speedplane\Documents\Work\2010 - 2011\Programs\DocketUpdater\..\DocketUpdater\libs\pdfminer\pdfparser.py", line 263, in __init__
    self.rotate = (self.attrs.get('Rotate', 0)+360) % 360
TypeError: unsupported operand type(s) for +: 'PDFObjRef' and 'int'
```

The problem is due to the code in pdfminer.pdfparser in the `PDFPage.__init__` function:
`self.rotate = (self.attrs.get('Rotate', 0)+360) % 360`

The problem arises when the Rotate field is an object reference instead of an integer.  When we add object references to an integer, we get an exception.  The solution is to change that line to the following:
`self.rotate = (resolve1(self.attrs.get('Rotate', 0))+360) % 360`

Here is the link to the PDF, perhaps useful for regression testing.

https://www.docketalarm.com/cases/International_Trade_Commission/337-850/Certain_Electronic_Imaging_Devices/491834/1/

**Comment by Gao06215712** [comment]
太厉害，感恩感谢
