### ISSUE TITLE
Latest build from PyPI doesn't have process_pdf

### ISSUE THREAD

**Issue by cglewis** [euske/pdfminer#34]
> > > from pdfminer.pdfinterp import PDFResourceManager, process_pdf
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: cannot import name process_pdf

This worked in the version prior to the one uploaded on 2013-11-13

**Comment by arishtanemi3007** [comment]
hello,
I'm trying to use PDFPage.get_pages() and it is showing a syntax error.

from pdfminer.pdfinterp import PDFPage.get_pages()
  File "<stdin>", line 1
    from pdfminer.pdfinterp import PDFPage.get_pages()
                                                                      ^
SyntaxError: invalid syntax

please assist.

**Comment by amnpawar** [comment]
@arishtanemi3007 from pdfminer.pdfpage import PDFPage should help your error go away
